# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/pensoft/articles/models/category/fields.yaml

# Model Class name
modelClass: Pensoft\Articles\Models\Category

# Default redirect location
defaultRedirect: pensoft/articles/categories

# Create page
create:
    title: backend::lang.form.create_title
    redirect: pensoft/articles/categories/update/:id
    redirectClose: pensoft/articles/categories

# Update page
update:
    title: backend::lang.form.update_title
    redirect: pensoft/articles/categories
    redirectClose: pensoft/articles/categories

# Preview page
preview:
    title: backend::lang.form.preview_title
